pub mod TestColor {
    use Chance.Color.rColor
    use Chance.Color

    //@Test
    //pub def testColor01(): Unit \ IO = 
    //    run {
    //        def loop(count: Int32) = {
    //            let (r, g, b) = Color.getRandomColorTriple();
    //            println(RichString.withColor(RichString.Color.Rgb(r, g, b), "This is a test for color (${r}, ${g}, ${b})"));
    //            if (count < 100) {loop(count + 1)} else {()}
    //        };
    //        loop(0)
    //    } with Color.runWithIO
}